# Prometheus configuration for monitoring FKS services
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'fks-trading'
    environment: 'production'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FKS API Service
  - job_name: 'fks-api'
    static_configs:
      - targets: ['fks-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # FKS Engine (Rust)
  - job_name: 'fks-engine'
    static_configs:
      - targets: ['fks-engine:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s  # More frequent for trading engine
    scrape_timeout: 3s

  # FKS NinjaTrader (.NET)
  - job_name: 'fks-ninja'
    static_configs:
      - targets: ['fks-ninja:8090']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-proxy:9113']
    metrics_path: '/metrics'

  # Node Exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
