
# Central orchestrator compose (migrated from fks/compose)
services:
  fks_api:
    build: ../../fks/fks_api
    container_name: fks_api
    env_file:
      - ../../fks/fks_api/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks: [core]

  fks_api_worker:
    build: ../../fks/fks_api
    container_name: fks_api_worker
    command: celery -A app.celery worker --loglevel=info --concurrency=1
    env_file:
      - ../../fks/fks_api/.env
    depends_on: [redis]
    networks: [core]

  fks_api_scheduler:
    build: ../../fks/fks_api
    container_name: fks_api_scheduler
    command: celery -A app.celery beat --loglevel=info
    env_file:
      - ../../fks/fks_api/.env
    depends_on: [redis]
    networks: [core]

  auth_server:
    image: ghcr.io/goauthelia/server:2024.8.3
    container_name: fks_auth_server
    depends_on: [postgres_auth, redis_auth]
    networks: [auth]
    environment:
      TZ: ${TZ:-UTC}
    ports:
      - "9000:9000"

  postgres:
    image: postgres:15-alpine
    container_name: fks_postgres
    environment:
      POSTGRES_USER: fks_user
      POSTGRES_PASSWORD: fks_secure_pass_2024!
      POSTGRES_DB: fks_trading
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks: [core]

  redis:
    image: redis:7-alpine
    container_name: fks_redis
    networks: [core]

  postgres_auth:
    image: postgres:15-alpine
    container_name: fks_auth_db
    environment:
      POSTGRES_USER: authelia
      POSTGRES_PASSWORD: authelia_secure_pass_2024!
      POSTGRES_DB: authelia
    volumes:
      - pg_auth_data:/var/lib/postgresql/data
    networks: [auth]

  redis_auth:
    image: redis:7-alpine
    container_name: fks_auth_redis
    networks: [auth]

networks:
  core:
  auth:

volumes:
  pg_data:
  pg_auth_data:
