# Production overrides (migrated)
services:
  fks_api:
    image: ${DOCKER_REGISTRY:-fks}/fks_api:${API_VERSION:-latest}
    environment:
      APP_ENV: production
      APP_LOG_LEVEL: WARNING
    deploy:
      resources:
        limits:
          cpus: "${API_CPU_LIMIT:-2}"
          memory: ${API_MEMORY_LIMIT:-2048M}
  fks_api_worker:
    image: ${DOCKER_REGISTRY:-fks}/fks_api:${API_VERSION:-latest}
    environment:
      APP_ENV: production
  fks_api_scheduler:
    image: ${DOCKER_REGISTRY:-fks}/fks_api:${API_VERSION:-latest}
    environment:
      APP_ENV: production
  auth_server:
    deploy:
      resources:
        limits:
          cpus: "${AUTH_CPU_LIMIT:-1}"
          memory: ${AUTH_MEMORY_LIMIT:-1024M}
  postgres:
    environment:
      POSTGRES_SHARED_BUFFERS: ${POSTGRES_SHARED_BUFFERS:-512MB}
  redis:
    command: >
      redis-server --appendonly yes --save 300 1 --loglevel warning
